### ISSUE TITLE
Checking integrity of apu2c4 firmware

### ISSUE THREAD

**Issue by Pferdebockwurst** [pcengines/coreboot#256] opened 2019-01-10 20:04 UTC
Hello everyone. I've bought a second hand apu2c4. How can I check and verify the integrity of the firmware (bios/coreboot)?

**Comment by pietrushnic** [comment] 2019-01-12 02:04
Hi @Pferdebockwurst, there is no easy way to do that. Mainly because we had no reproducible builds for coreboot - we will address that in the recent release which will be published this weekend (if I will find enough time).

Each firmware version that you can find [here](https://pcengines.github.io/) in the package has an MD5 sum file. So you can check the version of your firmware `dmidecode -t bios` or similar way, read SPI using flashrom and compare MD5 sum. There can be many problems even with that, first, there is bootorder file and various options in sortbootorder which are saved to SPI, your MD5 may be different. More to that you can use `cbfstool` to extract pieces and then compare those with one that you will get from the mentioned website.

This, of course, is not correct handling of the problem, because of that we will change the way we provide binary, then we will include SHA256 and signed SHA256 file, so anyone can have reasonable trust in what is downloaded.

**Comment by pietrushnic** [comment] 2019-01-12 10:32
@Pferdebockwurst yes, you are safe if you choose correct file for your platform. New firmware overwrite whole SPI flash, so nothing from previous firmware will persist.

**Comment by Pferdebockwurst** [comment] 2019-01-12 15:59
@pietrushnic Great, that's what I was hoping to hear. If flashing should fail I will be the recovery dongle.

Shall I close this issue?

**Comment by pietrushnic** [comment] 2019-01-12 18:01
@Pferdebockwurst great I could help. I will close this issue.

**Closed by pietrushnic** 2019-01-12 18:01 UTC
