### ISSUE TITLE
APU3 bios 4.6.1

### ISSUE THREAD

**Issue by riodda** [pcengines/coreboot#93] opened 2018-01-27 06:46 UTC
Hi, i've installed 4.6.1 on my new apu3 but i have the following issues:

Board Name is PC Engines apu3 instead of apu3 this seems to mess up OPENWRT modules for leds and gpio.
Sim reader seems to be not working, tested both sim slots.
Is possible to put also binaries for apu2 and apu3 in the releases ? 
Thanks.

**Comment by pietrushnic** [comment] 2018-01-27 19:13
Hi @riodda,
I believe LEDE changed drivers to match recent naming in SMBIOS tables. `PC Engines apu3` is correct name according to coreboot naming scheme and manufacturer requirements.

For SIM card sounds weird because we set that in v4.5.5: please check [changelog](https://github.com/pcengines/coreboot/blob/coreboot-4.6.x/CHANGELOG.md#v4552---2017-03-03). @miczyg1 maybe this SIM stuff is regression - please check that.

I'm not sure what binaries you mean - some were published [here](https://github.com/pcengines/apu2-documentation#mainline).

**Comment by riodda** [comment] 2018-01-27 20:33
I sorted the simcard issue, i had to tweak the board name in the leds2-apu2 and in the gpio-nct5104d.
About the bios binaries the latest avilable is 4.6.1 versus source 4.6.5.
I've tryed to build the source but is over my skills and i franly don't whant to risk the board with a bios i build myselt ! Would be nice to have the binaries for all the releases.
I've also noticed that on openwrt the  i2c support is broken, is it something that might be bios relatd ?

Thanks !

**Comment by miczyg1** [comment] 2018-01-28 11:43
Hello @riodda,
Could You please provide me more information?
What OpenWRT version did You use? I assume that the i2c problem is present on bios v4.6.1?

**Comment by sebastian-de** [comment] 2018-04-09 10:55
https://github.com/openwrt/openwrt/commit/7e42cbaf2a1e40cfdd1abde876a1bb66db784420
I submitted a patch for leds-apu2 in OpenWrt, which is now in master.
I don't use I2C, so I can't comment on that.

**Comment by nicklowe** [comment] 2018-04-15 17:42
Sebastian's patch has been committed to OpenWRT: https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=7e42cbaf2a1e40cfdd1abde876a1bb66db784420

**Comment by sebastian-de** [comment] 2018-04-16 10:10
@riodda 
Since coreboot v4.6.7 SMBIOS tables switched back to the old naming scheme, so I would recommend to install the latest release from https://pcengines.github.io/ and check whether the problems still occur.

**Comment by pietrushnic** [comment] 2018-05-18 19:28
@riodda can we close that bug?

**Comment by riodda** [comment] 2018-05-18 19:32
Haven't looked much in the matter, I think you can close it

Il ven 18 mag 2018, 20:28 Piotr Król <notifications@github.com> ha scritto:

**Comment by pietrushnic** [comment] 2018-05-20 23:06
Ok, closing.

**Closed by pietrushnic** 2018-05-20 23:06 UTC
