### ISSUE TITLE
AGESA ASSERT during boot

### ISSUE THREAD

**Issue by mek-x** [pcengines/coreboot#22] opened 2017-01-24 21:46 UTC
`ASSERTION ERROR: file 'src/northbridge/amd/pi/agesawrapper.c', line 305`

Right now, it's commented out, but this could be something to have in mind...

**Comment by thinrope** [comment] 2018-04-20 14:08
That sounds like a duplicate of issue #13 anyway ...

**Comment by pietrushnic** [comment] 2018-04-20 16:01
@thinrope thank you :)

**Closed by pietrushnic** 2018-04-20 16:01 UTC
